name: provaflutter_targetsistemas
description: Prova de flutter para a Target Sistemas.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.1
  mobx: ^2.2.1
  mobx_codegen: ^2.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
